language: java
services:
- docker

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
dd:
  secure: p+yqHd2VWIjzUYv287rTA2iVScJmcg6qj3oT5oV4f0MsNzXPVaqfJ5LL9r3X6CYCYPvDxqYjGSwth9F37ZNq3s+OMg0XiDFOHAP80HI24i4iO1gNU5akhfcgHtYGMLK+DmO1f9Lf+XaJQIYj0SO9E/aIAR+KXAin5ZYi6TmLO11OGkstDr9gPEcJisVanLD0lgGK1rfzcoywJ3kdpPwEKpm3VExk6LbvIBZp44sxzn7AykFiq4NPwc0IFXUxQNMRJyPMxVTXQ54kWu29KbQFz1G/NDVyRHfJmLSZD0QpaRZw2wIZoTDAL42aH3FgUoTyiJUdws8K8Q4zs4YE24v9+u8ceuFWNAVrj3MddZfgoz/wEEPSPbABry5HJkEZwKtLCFWc/Uun4g8VDHmgxA6FFB3XchtiGZg8g0mngy/iOt7F15jFJcM1eZ1Bc0GuUd4KUv23ZT1EhZ70yluL5R9OOxnkJf4WHVJ5U5Zmcm/zJlpCU3vG5o8SkbCo/t3/yiBxcBM54UXfoFI89WVjabN45zYqHyyZum3sQC6bpmuwJGNpXXPBa8qPhcbmNldvBOVyG5vsmUPfkFcEpg3PtXT+eLIwQLmSgT0sBSHerhnnCNXFCimq3scQgCcDmNokg+Sm9uzjd8gqNu5ZI2ot5wIsUNUa3GpX8p27066xKQyytgY=
